# Generated by Django 2.1.3 on 2018-11-11 01:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255, verbose_name='access token')),
                ('social_id', models.CharField(max_length=255, verbose_name='social id')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('profile_picture', models.CharField(max_length=500, verbose_name='profile picture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
    ]
